version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=ep-autumn-surf-a1ujcwbn-pooler.ap-southeast-1.aws.neon.tech
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=neondb
      - DB_POSTGRESDB_USER=neondb_owner
      - DB_POSTGRESDB_PASSWORD=npg_Ks8an5DSPCFl
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - ./n8n_data:/home/node/.n8n
